wust_binocular:
  ros__parameters:
    camera_config_file: /home/hy/wust_radar/src/wust_binocular/config/camera.yaml
    common:
      fps: 60
      use_trigger: false
      max_time_diff_ms: 5.0
      max_delay: 1.0
      use_binocular: false
      use_id_match: false
    detect:
      max_infer_threads: 3
      min_free_mem_ratio: 0.4
      config_path: /home/hy/wust_radar/src/wust_binocular/config/detect_params.yaml
    logger:
      log_level: INFO
      log_path: /home/hy/wust_log
      use_logcli: true
      use_logfile: true
      use_simplelog: true
