camera:
  target_sn: DA1094119
  acquisition_frame_rate: 80
  adc_bit_depth: Bits_12
  camera_info_path: /home/hy/wust_vision/config/camera_info.yaml
  exposure_time: 6000
  gain: 16.9
  gamma: 0.5 #Bayer用不了
  pixel_format: RGB8Packed #BayerRG8
  acquisition_frame_rate_enable: true
  reverse_x: false
  reverse_y: false
  recorder: true
  video_player:
    fps: 100
    loop: true
    #path: /home/hy/wust_data/video/222.MP4
    #path: /home/hy/wust_data/video/20250726_233351.avi
    path: /home/hy/data/ENTERPRIZE战队RM2025开源第一视角/7.27-华东理工.mp4
    #path: /home/hy/data/hndj.mp4
    #path: /home/hy/data/4k.MP4
    #path: /home/hy/wust_radar/src/wust_radar_detect/left_25.mp4
    #path: /home/hy/wust_data/video/jiao.avi
    #path: /home/hy/wust_data/video/rune.mp4
    #path: /home/hy/wust_data/video/Sentry.mp4
    start_frame: 4500
    alpha: 1.5
    beta: 5
    use: true
