type: video_player

camera_info_path: "/home/hy/wust_vision/config/camera_info.yaml"

hik_camera:
  target_sn: DA1094119 #DA3038891
  acquisition_frame_rate: 250
  adc_bit_depth: Bits_8
  exposure_time: 1300
  gain: 16.9
  gamma: 0.7 #Bayer用不了
  pixel_format: BayerRG8 #RGB8Packed
  acquisition_frame_rate_enable: true
  reverse_x: false
  reverse_y: false
  recorder: false

video_player:
  fps: 30
  loop: true
  path: /home/hy/data/ENTERPRIZE战队RM2025开源第一视角/7.27-华东理工.mp4
  start_frame: 6000
