yolo_path: /home/hy/wust_radar/src/wust_radar_detect/model/TensorRT/RM2025.engine
armor_path: /home/hy/wust_radar/src/wust_radar_detect/model/TensorRT/armor_yolo.engine
classify_path: /home/hy/wust_radar/src/wust_radar_detect/model/TensorRT/classify.engine
